[package]
name = "satty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = { version = "0.6.2", features = ["macros", "libadwaita"] }
relm4-icons = { version = "0.6.0", features = ["drop-regular", "arrow-redo-filled", "arrow-undo-filled", "save-regular", "copy-regular", "text-case-title-regular","text-font-regular","minus-large", "checkbox-unchecked-regular", "crop-filled", "arrow-up-right-filled", "rectangle-landscape-regular"] }
pangocairo = "0.17.10"
tokio = { version = "1.32.0", features = ["full"]}
gdk-pixbuf = "0.17.2"

# error handling
anyhow = "1.0"

# command line
clap = { version = "4.4.4", features = ["derive"] }
