[package]
name = "satty"
version = "0.8.1"
edition = "2021"
authors = ["Matthias Gabriel <gabm+aur@mailbox.org>"]
description = "A screenshot annotation tool inspired by Swappy and Flameshot."
homepage = "https://github.com/gabm/satty"
repository = "https://github.com/gabm/satty"
license = "MPL-2.0"
include = [
  "src/**/*",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "assets/",
]


[dependencies]
relm4 = { version = "0.6.2", features = ["macros", "libadwaita", "gnome_44"] }
pangocairo = "0.17.10"
tokio = { version = "1.32.0", features = ["full"] }
gdk-pixbuf = "0.17.2"

# error handling
anyhow = "1.0"

# command line
clap = { version = "4.4.10", features = ["derive"] }


[dependencies.relm4-icons]
version = "0.6.0"
features = [
  "pen-regular",
  "color-regular",
  "cursor-regular",
  "number-circle-1-regular",
  "drop-regular",
  "arrow-redo-filled",
  "arrow-undo-filled",
  "save-regular",
  "copy-regular",
  "text-case-title-regular",
  "text-font-regular",
  "minus-large",
  "checkbox-unchecked-regular",
  "crop-filled",
  "arrow-up-right-filled",
  "rectangle-landscape-regular",
]

[build-dependencies]
clap = { version = "4.4.10", features = ["derive"] }
clap_complete = "4.4.4"
clap_complete_nushell = "4.4.2"
clap_complete_fig = "4.4.2"
