[env]
PREFIX = {unset = true}

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = []

[tasks.install]
dependencies = ["build"]
script = '''
install -Dm755 target/release/satty -t ${PREFIX}/bin/
install -Dm644 satty.desktop ${PREFIX}/share/applications/satty.desktop
install -Dm644 assets/satty.svg ${PREFIX}/share/icons/hicolor/scalable/apps/satty.svg

install -Dm644 LICENSE ${PREFIX}/share/licenses/satty/LICENSE
'''


[tasks.uninstall]
script = '''
rm ${PREFIX}/bin/satty
rmdir -p ${PREFIX}/bin || true

rm ${PREFIX}/share/applications/satty.desktop
rmdir -p ${PREFIX}/share/applications || true

rm ${PREFIX}/share/icons/hicolor/scalable/apps/satty.svg
rmdir -p ${PREFIX}/share/icons/hicolor/scalable/apps || true

rm ${PREFIX}/share/licenses/satty/LICENSE
rmdir -p ${PREFIX}/share/licenses/satty || true
'''
